# Default values for aad-pod-identity-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# ex. helm install --dry-run --debug --set azureIdentity.name=,azureIdentity.namespace=,azureIdentity.resourceID=,azureIdentity.clientID=,azureIdentityBinding.name=,azureIdentityBinding.selector= <name_of_release> .

nameOverride: ""
fullnameOverride: ""

azureIdentity:
  name: 
  # if not defined, then the azure identity will be deployed in the same namespace as the chart
  namespace: 
  # type 0: MSI, type 1: Service Principal
  type: 0
  # /subscriptions/subscription-id/resourcegroups/resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-name
  resourceID: 
  clientID: 

azureIdentityBinding:
  name: 
  selector: 