apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-manager-sandbox.fullname" . }}-service
  labels:
    {{- include "cloud-manager-sandbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: communication
  selector:
    {{- include "cloud-manager-sandbox.selectorLabels" . | nindent 4 }}
