apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ required ".Values.azureIdentity.name is required!" .Values.azureIdentity.name }}
  namespace: {{ template "aad-pod-identity.azureidentity.namespace" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.azureIdentity.type }}
  ResourceID: {{ required ".Values.azureIdentity.resourceID is required!" .Values.azureIdentity.resourceID }}
  ClientID: {{ required ".Values.azureIdentity.clientID is required!" .Values.azureIdentity.clientID }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ required ".Values.azureIdentityBinding.name is required!" .Values.azureIdentityBinding.name }}
  namespace: {{ template "aad-pod-identity.azureidentitybinding.namespace" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
spec:
  AzureIdentity: {{ .Values.azureIdentity.name }}
  Selector: {{ required ".Values.azureIdentityBinding.selector is required!" .Values.azureIdentityBinding.selector }}