nameOverride:
fullnameOverride:
imageOverride:
certificateName:

environment:
sandboxId:
hostname:


replicaCount: 1
image:
  repository:
  name: terminal
  tag: latest
  pullPolicy: Always

podSecurityContext: {}

securityContext: {}

container:
  preStopSleepTime: "60"
  terminationGracePeriodSeconds: 86400 # one day

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

resources:
  limits:
    # cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 150m
    memory: 256Mi

nodeSelector: {}

env: {}
