nameOverride:
fullnameOverride:
imageOverride:
certificateName:

environment:
sandboxId:
hostname:


replicaCount: 1
image:
  repository:
  name: terminal
  tag: latest
  pullPolicy: Always

podSecurityContext: {}

securityContext: {}

container:
  preStopSleepTime: "120"
  terminationGracePeriodSeconds: 130

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

container:
  preStopSleepTime: "120"
  terminationGracePeriodSeconds: 130

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

env: {}
